import xarray as xr, pandas as pd, os
ds = xr.open_dataset("RF25_ind2025_rfp25.nc")
df = ds["RAINFALL"].to_dataframe().reset_index()
df = df.rename(columns={"TIME":"date","LATITUDE":"lat","LONGITUDE":"lon","RAINFALL":"rainfall_mm"})
df = df.dropna(subset=["rainfall_mm"])
df["date"] = df["date"].dt.date.astype("datetime64[ns]")
df["lat"] = df["lat"].astype("float32")
df["lon"] = df["lon"].astype("float32")
df["rainfall_mm"] = df["rainfall_mm"].astype("float32")
df = df[["date","lat","lon","rainfall_mm"]].sort_values(["date","lat","lon"]).reset_index(drop=True)
out = "RF25_ind2025_rfp25.parquet"
df.to_parquet(out, engine="pyarrow", compression="zstd", index=False)
print("rows", len(df))
print(df.head(3).to_string())
print("parquet MB", round(os.path.getsize(out)/1e6,2))
print("nc MB", round(os.path.getsize("RF25_ind2025_rfp25.nc")/1e6,2))
